name: Create Preview Release
on:
  push:
    branches:
      - "main"
      - "release/*"
jobs:
  main:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'
      - name: Try get cached dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Validate dependencies
        run: dotnet restore --locked-mode --packages ${{ github.workspace }}/.nuget/packages
      - name: Build
        run: dotnet msbuild -p:Configuration=Release -p:PublicRelease=false -graph -isolate -bl:artifacts/log/build.binlog
      - name: Test
        run: dotnet test --blame-crash --blame-hang --blame-hang-timeout 4m --logger "trx;LogFileName=TestResults.trx" --collect:"XPlat Code Coverage" --results-directory artifacts/test_results artifacts/bin/Tests/Release/net6.0/Tests.dll
      - name: Publish
        run: dotnet nuget push artifacts/**/*.nupkg --source 'https://nuget.pkg.github.com/pilchie/index.json' --api-key ${{secrets.NUGET_API_KEY }}

